name: Makefile CI

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: true

    - name: Install dependencies
      run: sudo apt install -y lua5.4

    - name: Run make dist
      run: make
      
    - name: Run test
      run: make test

    - name: tar dist files
      run: tar -cvf dist.tar dist

    # create nightly release
    - name: Create Nightly release
      if: ${{ github.repository == 'fxliang/charcode-lua' && github.ref == 'refs/heads/master' }}
      uses: 'marvinpinto/action-automatic-releases@latest'
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        prerelease: true
        title: "Nightly Build"
        files: |
          ./dist.tar
